### ISSUE TITLE
mesh-gateway doesn't support expansion of the environment variable HOST_IP

### ISSUE THREAD

**Issue by woz5999** [hashicorp/consul-dataplane#62]
We are attempting to upgrade to the latest version of consul-k8s that uses the consul-dataplane image for mesh-gateways. The new mesh-gateways are unable to start because they're not able to parse our `envoy_dogstatsd_url`. 

Error message:
```
failed to parse address udp://${HOST_IP}:8125
```

Our consul proxy-defaults config entry specifies:
```
envoy_dogstatsd_url   = "udp://${HOST_IP}:8125"
```

Per the documentation, expansion of this variable should be supported for `envoy_dogstatsd_url` and `envoy_statsd_url`: https://developer.hashicorp.com/consul/docs/connect/proxies/envoy#envoy_statsd_url

If I turn on debug logging, I can see that the envoy configuration is properly expanding the `HOST_IP` to the correct ip address:

```
  \"stats_sinks\": [
    {
      \"name\": \"envoy.stat_sinks.dog_statsd\",
      \"typedConfig\": {
        \"@type\": \"type.googleapis.com/envoy.config.metrics.v3.DogStatsdSink\",
        \"address\": {
          \"socket_address\": {
            \"address\": \"10.0.123.456\",
            \"port_value\": 8125
          }
        }
      }
    }
  ],
```

Here is where the error is being thrown: https://github.com/hashicorp/consul-dataplane/blob/main/pkg/consuldp/metrics.go#L359-L363

And here we can see that the address being passed to `parseSinkAddr` 
https://github.com/hashicorp/consul-dataplane/blob/main/pkg/consuldp/metrics.go#L152 is the raw value from the proxy-config, 
without the variable expansion.

The relevant path expansion takes place here for the envoy bootstrap config: https://github.com/hashicorp/consul-dataplane/blob/main/internal/bootstrap/bootstrap_config.go#L278-L284

I'm not too familiar with the new dataplane functionality and the distinction between the stats sync in the envoy config and the sink being setup in `metrics.go`. If the solution is as easy as copying/moving the variable expansion code into metrics, I'm happy to do that. But I'd like to ensure this is the right path first.

---
Note that the mesh-gateway deployment in the consul-k8s helm chart no longer provides the `HOST_IP` environment variable. The behavior above exists even if I manually update the deployment to add the variable, and I plan to submit a separate PR to that project to add the variable back. Of course this isn't directly relevant to the consul-dataplane project, but I wanted to be clear that the problem isn't simply that `HOST_IP` is unset.

**Comment by woz5999** [comment]
I added this functionality in consul previously in this PR: https://github.com/hashicorp/consul/pull/8564

@riddhi89 do you have an opinion on this?

**Comment by woz5999** [comment]
@david-yu any thoughts on this? i'm happy to make a PR but i'd like feedback from the dataplane team before proceeding.

**Comment by woz5999** [comment]
This is completely blocking our ability to upgrade to the latest version of consul-k8s. this breaks existing functionality and completely destroys our visibility into consul. This is a breaking change from the previous implementation. I'm happy to submit a PR to resolve this, but the lack of response does not make me inclined to put up the upfront work, not knowing if this is the correct direction or will even be seen.

**Comment by david-yu** [comment]
Hi @woz5999 I reviewed this issue with engineering and agreed that this should be considered as part of `consul-dataplane`. If you are able to make a PR for this within the week we can try to review it to be merged for an upcoming release next week.

**Comment by woz5999** [comment]
Thanks @david-yu . Much appreciated. PR is submitted.
